name: test
on: ["push"]
jobs: 
    run-shell-script:
         runs-on: ubuntu-latest
         steps:
           - name: run echo command
             run: echo  "Hello World"
           - name: run multilple command
             run: |
                node -v
                npm -v  
                uptime
                uname -a
                sleep 30
    run-window-command:
      runs-on: windows-latest
      steps:
        - name: directory12
          run: Get-Location
        - name: directorylocation
          run: pwd
          shell: bash
